# Generated by Django 4.0.5 on 2022-11-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_rename_imagen_productos_imagen1_productos_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='short_description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(max_length=4500),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='Productos'),
        ),
    ]
