# Generated by Django 4.0.6 on 2022-11-05 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_productos_short_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_section', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'seccion',
                'verbose_name_plural': 'secciones',
            },
        ),
        migrations.AlterField(
            model_name='productos',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.seccionproductos'),
        ),
    ]
