from django.urls import path
from django.conf import settings #Importamos el archivo settings.py desde la configuración de django.
from django.conf.urls.static import static #De ese archivo, importamos los estaticos.

#Importamos nuestras vistas:
from .views import (
    productos_favoritos,
    bolsocalavera,
    monturadecuero,
    botasmarrones,
    cascos,
    cascoargentina,
    cascosamarillos,
    casprint,
    cascoazul_f,
    cascoazul_m,
    CascoAzulyGris,
    CascoGris,
    cascobyn,
    cascobordo,
    cascobrilloso,
    cascocamuflado,
    cascochina,
    cascodegrade,
    cascopastel,
    cascoflores,
    cascogeometrico,
    cascogrisclaro,
    cascogrisazulado,
    cascoleon,
    cascogverde,
    cascoverde,
    cascogyc,
    cascomilitar,
    cascolobo,
    cascostones,
    cascoryb,
    cascorosab,
    cascotropical,
    cascovioleta,
    casconaranja,
    calzado,
    fundas,
    riendasyestribos,
    estribos,
    riendasnegras,
    riendas,
    monturas,
    bolsos,
    cinturon,
    cinturones,
    sobresincha,
    rodilleras,
    rodillerasadulto,
    rodillerasmujer,
    rodillerasniño,
    vendas,
    cascopastelverde,

)

app_name='Productos'
urlpatterns = [

    path('productos_favoritos/', productos_favoritos, name="favoritos"),
    path('bolsocalavera/', bolsocalavera, name="bolsocalavera"),
    path('monturadecuero/', monturadecuero, name="monturadecuero"),
    path('botasmarrones/', botasmarrones, name="botasmarrones"),
    path('cascoargentina/', cascoargentina, name="cascoargentina"),
    path('cascosamarillos/', cascosamarillos, name="cas-amarillos"),
    path('cascos/', cascos, name="cascos"),
    path('casprint/', casprint, name="cas-print"),
    path('cascoazul_f/', cascoazul_f, name="cascoazul_f"),
    path('cascoazul_m/', cascoazul_m, name="cascoazul_m"),
    path('cascoazulygris/', CascoAzulyGris, name="cascoazulygris"),
    path('cascogris/', CascoGris, name="cascogris"),
    path('cascobyn/', cascobyn, name="cascobyn"),
    path('cascobordo/', cascobordo, name="cascobordo"),
    path('cascobrilloso/', cascobrilloso, name="cascobrilloso"),
    path('cascocamuflado/', cascocamuflado, name="cascocamuflado"),
    path('cascochina/', cascochina, name="cascochina"),
    path('cascodegrade/', cascodegrade, name="cascodegrade"),
    path('cascopastel/', cascopastel, name="cascopastel"),
    path('cascoflores/', cascoflores, name="cascoflores"),
    path('cascogeometrico/', cascogeometrico, name="cascogeometrico"),
    path('cascogrisclaro/', cascogrisclaro, name="cascogrisclaro"),
    path('cascogrisazulado/', cascogrisazulado, name="cascoga"),
    path('cascoleon/', cascoleon, name="cascoleon"),
    path('cascogverde/', cascogverde, name="cascogverde"),
    path('cascopastel/', cascopastelverde, name="cascopastelverde"),
    path('cascogyc/', cascogyc, name="cascogyc"),
    path('cascomilitar/', cascomilitar, name="cascomilitar"),
    path('cascolobo/', cascolobo, name="cascolobo"),
    path('cascostones/', cascostones, name="cascostones"),
    path('cascoverde/', cascoverde, name="cascoverde"),
    path('cascotropical/', cascotropical, name="cascotropical"),
    path('cascoryb/', cascoryb, name="cascoryb"),
    path('cascorosab/', cascorosab, name="cascorosab"),
    path('cascovioleta/', cascovioleta, name="cascovioleta"),
    path('casconaranja/', casconaranja, name="casconaranja"),
    path('calzado/', calzado, name="calzado"),
    path('fundas/', fundas, name="fundas"),
    path('estribos/', estribos, name="estribos"),
    path('riendasyestribos/', riendasyestribos, name="riendasyestribos"),
    path('riendasnegras/', riendasnegras, name="riendasnegras"),
    path('riendas/', riendas, name="riendas"),
    path('monturas/', monturas, name="monturas"),
    path('bolsos/', bolsos, name="bolsos"),
    path('cinturones/', cinturones, name="cinturones"),
    path('cinturon/', cinturon, name="cinturon"),
    path('sobresincha/', sobresincha, name="sobresincha"),
    path('rodillerasadulto/', rodillerasadulto, name="rodillerasadulto"),
    path('rodillerasmujer/', rodillerasmujer, name="rodillerasmujer"),
    path('rodillerasniño/', rodillerasniño, name="rodillerasniño"),
    path('rodilleras/', rodilleras, name="rodilleras"),
    path('vendas/', vendas, name="vendas"),
]
